### ISSUE TITLE
How to get formatted dates in a field?

### ISSUE THREAD

**Issue by nkrumm** [plaitpy/plaitpy#3]
I am trying to do something like the following using the `datetime` library:
```yaml
define:
  now: time.time()
  max_offset: 60 * 1000

fields:
  _offset:
    random: (random() * $max_offset) - ($max_offset / 2)

  time:
    lambda: str(datetime.datetime.utcfromtimestamp($now + this._offset))

hide:
  - offset
```
But this always returns `None`. Is there something specific with using `datetime`?

Thanks-- love this package btw!

**Comment by okayzed** [comment]
ok, sorry about that!

if you run your command with: `DEBUG=1 plait.py mytemplate.yaml`, you will see an error that datetime is not defined.

to fix it, you can do:

```
define:
  now: time.time()
  max_offset: 60 * 1000

fields:
  _offset:
    random: (random() * $max_offset) - ($max_offset / 2)

  time:
    lambda: str(datetime.datetime.utcfromtimestamp($now + this._offset))

hide:
  - offset

imports:
  - datetime
```
